---
title: The SUBSTATION
timezone: Australia/Melbourne
collections:
  about:
    title: About us
    output: true
  posts:
    title: Events
    output: true
  residents:
    title: Residents
    output: true
  supporters:
    title: Supporters
    output: false
  uploads:
    title: Uploads
    output: false
  venues:
    title: Venues
    output: true
defaults:
- scope:
    path: ''
    type: Supporters
  values:
    portrait-ratio: false
    organisational: 
    program: 
    presenting: 
- scope:
    path: ''
    type: about
  values:
    layout: post
    permalink: "/:collection/:path/"
    is-visible: true
    is-half-hero: false
- scope:
    path: ''
    type: residents
  values:
    layout: post
    permalink: "/:collection/:path/"
    position: 
- scope:
    path: ''
    type: venues
  values:
    layout: post
    permalink: "/:collection/:path/"
    venue-cta: true
- scope:
    path: ''
    type: hidden
  values:
    layout: protected-page
    permalink: "/:collection/:path/"
- scope:
    path: ''
    type: pages
  values:
    layout: post
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/:categories/:title/"
    has-javascripts: true
    was-in-development: false
    title: 
    categories: 
    image: 
    image-credit: 
    video: 
    video-thumbnail: 
    button-url: 
    button-txt: Book now
    presented-by: false
    tagline: false
    price: false
    datetime: 
    is-on-home-page: false
    has-opening-event: false
    has-preview-event: false
    has-closing-event: false
    has-start-time: false
    has-mins: false
    is-single-date: false
    is-list-of-dates: false
    is-opening-hours-time: false
    is-single-time-duration: false
    is-single-month-duration: false
    is-many-months-duration: false
    is-year-duration: false
    is-within-gallery-open-time: false
    event-duration-txt: 
    artists-talk:
      date: 
      note: 
    notes:
      date: 
      note: 
    supporters: 
description: The SUBSTATION is a unique large-scale multi-purpose gallery, performance
  space and dance studio for artists of every kind, in Newport, Melbourne, Australia.
baseurl: 
url: https://thesubstation.org.au
logo: "/uploads/the-substation-logo.png"
facebook:
  username: TheSubstationNewport
twitter:
  username: thesubstation_
social:
  name: The SUBSTATION
  links:
  - https://www.facebook.com/TheSubstationNewport/
  - https://www.instagram.com/thesubstation/
  - https://twitter.com/thesubstation_
  - https://www.linkedin.com/company/the-substation-newport/
author: Callum Flack Design
address: 1 Market Street, Newport
address-second: Victoria 3015, Australia
address-link: https://goo.gl/maps/WG1MkodsgHP2
phone: "(03) 9391 1110"
email: info@thesubstation.org.au
email-events: events@thesubstation.org.au
gallery-hours: Tuesday - Saturday, 11am - 5pm
office-hours: Monday - Friday, 9am - 5pm
events-manager: Marisa Fiume
google-analytics: UA-79358718-1
imageurl: "/dist/images/"
uploadurl: "/uploads/"
javascriptsurl: "/dist/scripts/"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
exclude:
- assets/_source
- Gemfile.lock
- ".gitignore"
- editorconfig
- gulpfile.js
- package.json
- node_modules
- yarn.lock
- README*
